<?php
/**
 * DidPurchaseResponseDidTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ilinaya SMSFlow
 *
 * Ilinaya SMSFlow API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: all@ilinaya.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DidPurchaseResponseDidTest Class Doc Comment
 *
 * @category    Class
 * @description DidPurchaseResponseDid
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DidPurchaseResponseDidTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DidPurchaseResponseDid"
     */
    public function testDidPurchaseResponseDid()
    {
    }

    /**
     * Test attribute "did_number"
     */
    public function testPropertyDidNumber()
    {
    }

    /**
     * Test attribute "monthly_fee"
     */
    public function testPropertyMonthlyFee()
    {
    }

    /**
     * Test attribute "activation_fee"
     */
    public function testPropertyActivationFee()
    {
    }

    /**
     * Test attribute "next_billing_date"
     */
    public function testPropertyNextBillingDate()
    {
    }
}
