<?php
/**
 * PurchaseHistoryItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ilinaya SMSFlow
 *
 * Ilinaya SMSFlow API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: all@ilinaya.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PurchaseHistoryItemTest Class Doc Comment
 *
 * @category    Class
 * @description PurchaseHistoryItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PurchaseHistoryItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PurchaseHistoryItem"
     */
    public function testPurchaseHistoryItem()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "purchase_type"
     */
    public function testPropertyPurchaseType()
    {
    }

    /**
     * Test attribute "amt"
     */
    public function testPropertyAmt()
    {
    }

    /**
     * Test attribute "balance_before"
     */
    public function testPropertyBalanceBefore()
    {
    }

    /**
     * Test attribute "balance_after"
     */
    public function testPropertyBalanceAfter()
    {
    }

    /**
     * Test attribute "did"
     */
    public function testPropertyDid()
    {
    }

    /**
     * Test attribute "package"
     */
    public function testPropertyPackage()
    {
    }

    /**
     * Test attribute "organization_user"
     */
    public function testPropertyOrganizationUser()
    {
    }
}
