<?php
/**
 * PackagesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ilinaya SMSFlow
 *
 * Ilinaya SMSFlow API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: all@ilinaya.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PackagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PackagesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for packagesBuyPost
     *
     * Purchase sms package.
     *
     */
    public function testPackagesBuyPost()
    {
    }

    /**
     * Test case for packagesGet
     *
     * Retrieve available packages.
     *
     */
    public function testPackagesGet()
    {
    }

    /**
     * Test case for packagesHistoryGet
     *
     * Get sms package number purchase history.
     *
     */
    public function testPackagesHistoryGet()
    {
    }
}
